## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application2_df = application_df.drop(columns = ["EIN", "NAME"])

In [3]:
application2_cat = application2_df.dtypes[application2_df.dtypes == "object"].index.tolist()
application2_df[application2_cat].nunique()

APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
ORGANIZATION               4
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
dtype: int64

In [4]:
# create dataframe of number of each type of application
count_types_df = pd.DataFrame(application2_df["APPLICATION_TYPE"].value_counts())
count_types_df

     APPLICATION_TYPE
T3              27037
T4               1542
T6               1216
T5               1173
T19              1065
T8                737
T7                725
T10               528
T9                156
T13                66
T12                27
T2                 16
T25                 3
T14                 3
T29                 2
T15                 2
T17                 1

In [5]:
#get the list of the top ten most common application types
most_common = application2_df["APPLICATION_TYPE"].value_counts()[:10]
most_common

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# create a list of application types (named application_types_to_replace) that lists those with fewer than 200 of that type
application_types_to_replace = []
for row in range (len(count_types_df)):
  if (count_types_df['APPLICATION_TYPE'][row] < 200):
    application_types_to_replace.append(count_types_df.index[row])

application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [7]:
# Replace in dataframe
for app in range (len(application_types_to_replace)):
    application2_df['APPLICATION_TYPE'] = application2_df['APPLICATION_TYPE'].replace(application_types_to_replace[app],"Other")

# Check to make sure binning was successful
application2_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classify_count_df = pd.DataFrame(application2_df['CLASSIFICATION'].value_counts())

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
application2_df['CLASSIFICATION'].value_counts().loc[lambda x : x > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced; cutoff value of 50 selected
# use the variable name `classifications_to_replace`
classification_types_to_replace = []
for row in range (len(classify_count_df)):
  if (classify_count_df['CLASSIFICATION'][row] < 51):
    classification_types_to_replace.append(classify_count_df.index[row])


# Replace in dataframe
for cls in classification_types_to_replace:
    application2_df['CLASSIFICATION'] = application2_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application2_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1197
C7000      777
C1700      287
Name: CLASSIFICATION, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummy_df = pd.get_dummies(application2_df, columns = ['INCOME_AMT', 'SPECIAL_CONSIDERATIONS', 'AFFILIATION', 'USE_CASE', 'ORGANIZATION', 'CLASSIFICATION', 'APPLICATION_TYPE'])

In [ ]:
application_dummy_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,...,CLASSIFICATION_Other,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,1,108590,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [14]:
# Split our preprocessed data into our features and target arrays
y = application_dummy_df.IS_SUCCESSFUL.values
X = application_dummy_df.drop(columns = 'IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 1, stratify = y)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [42]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=77, activation="relu", input_dim=45))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="relu"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_22"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_49 (Dense)            (None, 77)                3542

 dense_50 (Dense)            (None, 30)                2340

 dense_51 (Dense)            (None, 1)                 31

=================================================================
Total params: 5913 (23.10 KB)
Trainable params: 5913 (23.10 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [43]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [44]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 1.1336 - accuracy: 0.6911
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 1.3220 - accuracy: 0.6892
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 1.3894 - accuracy: 0.6901
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.9786 - accuracy: 0.7124
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.9230 - accuracy: 0.7147
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 1.0311 - accuracy: 0.7059
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 1.2166 - accuracy: 0.6916
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7926 - accuracy: 0.7104
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.8294 - accuracy: 0.7123
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7156 - accuracy: 0.7179
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7935 - accuracy: 0.7135
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.8849 - accuracy: 0.7087
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7887 - accuracy: 0.7195
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.7860 - accuracy: 0.7180
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7425 - accuracy: 0.7224
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6962 - accuracy: 0.7261
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7093 - accuracy: 0.7214
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6816 - accuracy: 0.7283
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6992 - accuracy: 0.7279
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6997 - accuracy: 0.7271
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.7294 - accuracy: 0.7262
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.7046 - accuracy: 0.7220
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6809 - accuracy: 0.7312
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6750 - accuracy: 0.7294
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6753 - accuracy: 0.7314
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6751 - accuracy: 0.7306
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6871 - accuracy: 0.7310
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6806 - accuracy: 0.7242
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6591 - accuracy: 0.7318
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6598 - accuracy: 0.7316
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6437 - accuracy: 0.7314
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6516 - accuracy: 0.7280
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6297 - accuracy: 0.7259
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6071 - accuracy: 0.7290
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6254 - accuracy: 0.7311
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6355 - accuracy: 0.7313
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6298 - accuracy: 0.7299
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6398 - accuracy: 0.7307
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6352 - accuracy: 0.7316
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6312 - accuracy: 0.7315
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6352 - accuracy: 0.7309
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6254 - accuracy: 0.7313
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6277 - accuracy: 0.7290
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6105 - accuracy: 0.7332
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6087 - accuracy: 0.7306
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5899 - accuracy: 0.7310
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5824 - accuracy: 0.7343
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5828 - accuracy: 0.7343
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5880 - accuracy: 0.7327
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5871 - accuracy: 0.7334
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5947 - accuracy: 0.7276
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5917 - accuracy: 0.7341
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6025 - accuracy: 0.7332
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6056 - accuracy: 0.7341
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6053 - accuracy: 0.7325
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6121 - accuracy: 0.7323
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6281 - accuracy: 0.7116
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5975 - accuracy: 0.7303
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5955 - accuracy: 0.7338
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5917 - accuracy: 0.7348
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5939 - accuracy: 0.7341
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5997 - accuracy: 0.7301
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5961 - accuracy: 0.7345
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5981 - accuracy: 0.7347
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5919 - accuracy: 0.7330
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5879 - accuracy: 0.7333
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5928 - accuracy: 0.7335
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5841 - accuracy: 0.7337
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5855 - accuracy: 0.7351
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5949 - accuracy: 0.7281
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5835 - accuracy: 0.7301
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5827 - accuracy: 0.7333
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5783 - accuracy: 0.7358
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5848 - accuracy: 0.7310
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5827 - accuracy: 0.7339
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5780 - accuracy: 0.7356
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5747 - accuracy: 0.7356
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5814 - accuracy: 0.7357
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5860 - accuracy: 0.7316
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5830 - accuracy: 0.7339
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5932 - accuracy: 0.7299
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5863 - accuracy: 0.7334
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5926 - accuracy: 0.7310
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5823 - accuracy: 0.7341
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5899 - accuracy: 0.7350
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5933 - accuracy: 0.7308
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5823 - accuracy: 0.7348
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5840 - accuracy: 0.7349
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5831 - accuracy: 0.7346
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5964 - accuracy: 0.7264
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6148 - accuracy: 0.7103
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6072 - accuracy: 0.7202
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5907 - accuracy: 0.7347
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6062 - accuracy: 0.7214
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5937 - accuracy: 0.7326
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5900 - accuracy: 0.7310
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5902 - accuracy: 0.7291
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5902 - accuracy: 0.7305
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5812 - accuracy: 0.7354
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5830 - accuracy: 0.7354

In [45]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6255 - accuracy: 0.7278 - 479ms/epoch - 2ms/step
Loss: 0.6254507303237915, Accuracy: 0.7278134226799011

In [47]:
# Export our model to HDF5 file
nn_model.save_weights('AlphabetSoupCharity_Optimization.h5')